export const projects = [
  {
    name: "Yana Gorina",
    project: "Connect Four	",
    link: "https://github.com/YanaGorina-alt/connect-four-project	",
    gamelink: "https://yanagorina-alt.github.io/connect-four-project/",
  },
  {
    name: "Annson Cook",
    project: "Blackjack",
    link: "https://github.com/Fiestaman/blackjack	",
    gamelink: "https://fiestaman.github.io/blackjack/",
  },
  {
    name: "Gino Torres",
    project: "Guess the image	",
    link: "https://gindogg878.github.io/GuessTheImage/	",
  },
  {
    name: "Naomi Clark",
    project: "The Color Game	",
    link: "https://github.com/itsnaomi7/The-Color-Game	",
    gamelink: "https://itsnaomi7.github.io/The-Color-Game/",
  },
  {
    name: "Nicolas Davis",
    project: "The Oregon Trail	",
    link: "https://github.com/nd1391/Mod1-Proj-Trail-Best	",
    gamelink: "https://nd1391.github.io/Mod1-Proj-Trail-Best/",
  },
  {
    name: "Jeffrey Lim",
    project: "Tic Tac Toe	",
    link: "https://github.com/Jeffinitely00/tictactoe	",
    gamelink: "https://jeffinitely00.github.io/tictactoe/",
  },
  {
    name: "Yuan Wu",
    project: "Farkle	",
    link: "https://github.com/yuanwuu/farkle-dice-game	",
    gamelink: "https://yuanwuu.github.io/farkle-dice-game/",
  },
  {
    name: "Stanley Louie",
    project: "Know Your Pepes	",
    link: "https://github.com/Iouie/Know-Your-Pepe	",
    gamelink: "https://iouie.github.io/Know-Your-Pepe/",
  },
  {
    name: "Ramya Putta",
    project: "The  Pet Story	",
    link: "https://github.com/rams446/Project-Basedon-Story.git	",
    gamelink: "https://rams446.github.io/Project-Basedon-Story/",
  },
  {
    name: "Lauren Camin",
    project: "Calixto	Jeopardy 	",
    link: "https://github.com/laurencamin/jeopardymodone.git	",
  },
  {
    name: "Devin Hansen",
    project: "Choose Your Own Adventure Game/Story	",
    link: "https://github.com/caution73/mod1_story_project	",
    gamelink: "https://caution73.github.io/mod1_story_project/",
  },
  {
    name: "Edwin Rodela",
    project: "Gladiator RPG	",
    link: "https://github.com/Erodela/Module1-Project-Gladiator-RPG	",
    gamelink: "https://erodela.github.io/Module1-Project-Gladiator-RPG/",
  },
  {
    name: "Blake Zaide",
    project: "Hangman	",
    link: "https://github.com/Blake-715/Hangman	",
  },
  {
    name: "Abdul Rahman",
    project: "Candy Crush	",
    link: "https://github.com/Abdul-XCI/candyCrushProject	",
    gamelink: "https://abdul-xci.github.io/",
  },
  {
    name: "Olga Sarukhanova",
    project: "Easter is coming!	",
    link: "https://github.com/Olygen/W6project	",
  },
  {
    name: "Luis Lugo",
    project: "Whac-a-Mole	",
    link: "https://github.com/luisRlugo/Whac-a-Pain	",
    gamelink: "https://luisrlugo.github.io/Whac-a-Pain/",
  },
  {
    name: "Anthony Cheung",
    project: "Dungeon Crawler	",
    link: "https://github.com/ranylm/MOD1-Dungeon-Crawler	",
    gamelink: "https://ranylm.github.io/MOD1-Dungeon-Crawler/",
  },
  {
    name: "BrayanPerez	Maze",
    project: "Game	",
    link: "https://brayancx.github.io/NBA-MAZE-PROJECT/	",
  },
  {
    name: "Arwa Sharif",
    project: "Find the Hidden Objects	",
    link: "https://github.com/ArwaSharif/Mod1Project-HiddenObjects	",
    gamelink: "https://arwasharif.github.io/Mod1Project-HiddenObjects/",
  },
  {
    name: "Michael Charime",
    project: "	Adventures of Baby Yoda	",
    link: "https://github.com/Mc816/DOM-Final-Project.git	",
    gamelink: "https://mc816.github.io/DOM-Final-Project/",
  },
  {
    name: "Joshua Paul",
    project: "	Minefield	",
    link: "https://github.com/Joshua-P-GitHub/MineField.github.io	",
    gamelink: "https://joshua-p-github.github.io/MineField.github.io/",
  },
  {
    name: "Jacqueline Barragan",
    project: "Lomeli	Rock Paper Scissors	",
    link: "https://github.com/barrajac/rock-paper-scissors-game.git	",
    gamelink: "https://barrajac.github.io/rock-paper-scissors-game/",
  },
  {
    name: "Jennifer Nguyen",
    project: "High or low	",
    link: "https://github.com/jnttt/w6-high-or-low	",
    gamelink: "https://jnttt.github.io/",
  },
  {
    name: "Nikita Rama",
    project: "Tetris	",
    link: "https://github.com/RamaNikita/Project-Game.git	",
    gamelink: "https://ramanikita.github.io/Project-Game/",
  },
  {
    name: "Candra McGill",
    project: "Jeopardy	",
    link: "https://github.com/cmcgill436/Mod-1-Jeopardy-Project	",
    gamelink:
      "https://cmcgill436.github.io/Mod-1-Jeopardy-Project/project-jeopardy/index.html",
  },
  {
    name: "Delfina Gist",
    project: "Memory Match	",
    link: "https://github.com/DelfinaGist	",
    gamelink: "https://DelfinaGist.github.io/MemoryMatch/",
  },
];
