export const projects = [
  {
    name: "YanaGorina",
    project: "ConnectFour",
    link: "https://github.com/YanaGorina-alt/connect-four-project",
    gamelink: "https://yanagorina-alt.github.io/connect-four-project/",
  },
  {
    name: "AnnsonCook",
    project: "Blackjack",
    link: "https://github.com/Fiestaman/blackjack",
    gamelink: "https://fiestaman.github.io/blackjack/",
  },
  {
    name: "GinoTorres",
    project: "Guesstheimage",
    link: "https://gindogg878.github.io/GuessTheImage/",
  },
  {
    name: "NaomiClark",
    project: "TheColorGame",
    link: "https://github.com/itsnaomi7/The-Color-Game",
    gamelink: "https://itsnaomi7.github.io/The-Color-Game/",
  },
  {
    name: "NicolasDavis",
    project: "TheOregonTrail",
    link: "https://github.com/nd1391/Mod1-Proj-Trail-Best",
    gamelink: "https://nd1391.github.io/Mod1-Proj-Trail-Best/",
  },
  {
    name: "JeffreyLim",
    project: "TicTacToe",
    link: "https://github.com/Jeffinitely00/tictactoe",
    gamelink: "https://jeffinitely00.github.io/tictactoe/",
  },
  {
    name: "YuanWu",
    project: "Farkle",
    link: "https://github.com/yuanwuu/farkle-dice-game",
    gamelink: "https://yuanwuu.github.io/farkle-dice-game/",
  },
  {
    name: "StanleyLouie",
    project: "KnowYourPepes",
    link: "https://github.com/Iouie/Know-Your-Pepe",
    gamelink: "https://iouie.github.io/Know-Your-Pepe/",
  },
  {
    name: "RamyaPutta",
    project: "ThePetStory",
    link: "https://github.com/rams446/Project-Basedon-Story.git",
    gamelink: "https://rams446.github.io/Project-Basedon-Story/",
  },
  {
    name: "LaurenCamin",
    project: "CalixtoJeopardy",
    link: "https://github.com/laurencamin/jeopardymodone.git",
  },
  {
    name: "DevinHansen",
    project: "ChooseYourOwnAdventureGame/Story",
    link: "https://github.com/caution73/mod1_story_project",
    gamelink: "https://caution73.github.io/mod1_story_project/",
  },
  {
    name: "EdwinRodela",
    project: "GladiatorRPG",
    link: "https://github.com/Erodela/Module1-Project-Gladiator-RPG",
    gamelink: "https://erodela.github.io/Module1-Project-Gladiator-RPG/",
  },
  {
    name: "BlakeZaide",
    project: "Hangman",
    link: "https://github.com/Blake-715/Hangman",
  },
  {
    name: "AbdulRahman",
    project: "CandyCrush",
    link: "https://github.com/Abdul-XCI/candyCrushProject",
    gamelink: "https://abdul-xci.github.io/",
  },
  {
    name: "OlgaSarukhanova",
    project: "Easteriscoming!",
    link: "https://github.com/Olygen/W6project",
  },
  {
    name: "LuisLugo",
    project: "Whac-a-Mole",
    link: "https://github.com/luisRlugo/Whac-a-Pain",
    gamelink: "https://luisrlugo.github.io/Whac-a-Pain/",
  },
  {
    name: "AnthonyCheung",
    project: "DungeonCrawler",
    link: "https://github.com/ranylm/MOD1-Dungeon-Crawler",
    gamelink: "https://ranylm.github.io/MOD1-Dungeon-Crawler/",
  },
  {
    name: "BrayanPerezMaze",
    project: "Game",
    link: "https://brayancx.github.io/NBA-MAZE-PROJECT/",
  },
  {
    name: "ArwaSharif",
    project: "FindtheHiddenObjects",
    link: "https://github.com/ArwaSharif/Mod1Project-HiddenObjects",
    gamelink: "https://arwasharif.github.io/Mod1Project-HiddenObjects/",
  },
  {
    name: "MichaelCharime",
    project: "AdventuresofBabyYoda",
    link: "https://github.com/Mc816/DOM-Final-Project.git",
    gamelink: "https://mc816.github.io/DOM-Final-Project/",
  },
  {
    name: "JoshuaPaul",
    project: "Minefield",
    link: "https://github.com/Joshua-P-GitHub/MineField.github.io",
    gamelink: "https://joshua-p-github.github.io/MineField.github.io/",
  },
  {
    name: "JacquelineBarragan",
    project: "LomeliRockPaperScissors",
    link: "https://github.com/barrajac/rock-paper-scissors-game.git",
    gamelink: "https://barrajac.github.io/rock-paper-scissors-game/",
  },
  {
    name: "JenniferNguyen",
    project: "Highorlow",
    link: "https://github.com/jnttt/w6-high-or-low",
    gamelink: "https://jnttt.github.io/",
  },
  {
    name: "NikitaRama",
    project: "Tetris",
    link: "https://github.com/RamaNikita/Project-Game.git",
    gamelink: "https://ramanikita.github.io/Project-Game/",
  },
  {
    name: "CandraMcGill",
    project: "Jeopardy",
    link: "https://github.com/cmcgill436/Mod-1-Jeopardy-Project",
    gamelink:
      "https://cmcgill436.github.io/Mod-1-Jeopardy-Project/project-jeopardy/index.html",
  },
  {
    name: "DelfinaGist",
    project: "MemoryMatch",
    link: "https://github.com/DelfinaGist",
    gamelink: "https://DelfinaGist.github.io/MemoryMatch/",
  },
];
